const Enum = require('enum');

const responseCodes = new Enum({
  VALID: 'VALID',
  CREATE_RECORD_SUCCESS: 'CREATE_RECORD_SUCCESS',
  UPDATE_RECORD_SUCCESS: 'UPDATE_RECORD_SUCCESS',
  DELETE_RECORD_SUCCESS: 'DELETE_RECORD_SUCCESS',
  PROCESS_RECORD_SUCCESS: 'PROCESS_RECORD_SUCCESS',
  RECORD_FOUND: 'RECORD_FOUND',
  RETRIEVE_RECORD_LIST: 'RETRIEVE_RECORD_LIST',
  ERROR_PROCESSING: 'ERROR_PROCESSING',
  DATA_PROCESSING_ERROR: 'DATA_PROCESSING_ERROR',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  AUTHENTICATION_FAILED: 'AUTHENTICATION_FAILED',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
});

const validationCodes = new Enum({
  INVALID_PARAMETER: 'INVALID_PARAMETER',
  MISSING_FIELDS: 'MISSING_FIELDS',
  RECORD_NOT_FOUND: 'RECORD_NOT_FOUND',
  RECORD_ALREADY_EXISTS: 'RECORD_ALREADY_EXISTS',
});

const ResponseCodes = { ...responseCodes, ...validationCodes };

module.exports = ResponseCodes;
